api 16
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

diff --git a/.github/workflows/garm.yml b/.github/workflows/garm.yml
--- a/.github/workflows/garm.yml
+++ b/.github/workflows/garm.yml
@@ -24,7 +24,7 @@ jobs:
             fail-fast: false
             matrix:
                 server: [ master, stable29 ]
-                api-level: [ 15, 27 ]
+                api-level: [ 16, 27 ]
         steps:
             -   uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
 
@@ -73,7 +73,102 @@ jobs:
                     echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > $HOME/.gradle/gradle.properties
                     echo "org.gradle.caching=true" >> $HOME/.gradle/gradle.properties
 
-            -   name: Build gplay
+            -   name: Build gplay # TODO build only once!
+                run: |
+                    sed -i s#https://server#http://10.0.2.2# gradle.properties
+                    sed -i s"#1#5#" ./library/src/androidTest/java/com/owncloud/android/RetryTestRule.kt
+                    ./gradlew assembleDebug
+
+            -   name: gplay
+                env:
+                    SHOT_TEST: "true"
+                uses: reactivecircus/android-emulator-runner@6b0df4b0efb23bb0ec63d881db79aefbc976e4b2 # v2.30.1
+                with:
+                    api-level: ${{ matrix.api-level }}
+                    force-avd-creation: false
+                    arch: x86
+                    sdcard-path-or-size: 100M
+                    target: google_apis
+                    emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -skin 500x833
+                    script: scripts/runTests.sh
+
+            -   name: upload failing results
+                if: ${{ failure() }}
+                env:
+                    LOG_USERNAME: ${{ secrets.LOG_USERNAME }}
+                    LOG_PASSWORD: ${{ secrets.LOG_PASSWORD }}
+                    GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
+                    GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
+                run: scripts/uploadReport.sh "${{ secrets.LOG_USERNAME }}"  "${{ secrets.LOG_PASSWORD }}"   ${{github.event.number}}    "master" "IT" ${{github.event.number}} "${{ secrets.GIT_USERNAME }}" "${{ secrets.GIT_TOKEN }}"
+            -   name: Archive Espresso results
+                uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
+                if: ${{ always() }}
+                with:
+                    name: Report-${{ matrix.server }}-${{ matrix.api-level }}
+                    path: app/build/reports
+                    retention-days: 4
+
+    stable16:
+        runs-on: ubuntu-22.04 # our own GARM does not yet support it
+        services:
+            server:
+                image: nextcloudci/server:server-13
+                options: --name server
+                ports:
+                    - 80:80
+        strategy:
+            fail-fast: false
+            matrix:
+                api-level: [ 27 ]
+        steps:
+            -   uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+
+            -   name: wait and ping server
+                run: |
+                    while ! curl http://localhost/status.php 2>&1 | grep installed; do
+                        echo "wait…"
+                        sleep 5
+                    done
+
+            -   name: configure server
+                run: |
+                    docker cp .github/workflows/configServer.sh server:/tmp/
+                    docker exec server chmod +x /tmp/configServer.sh
+                    docker exec server /tmp/configServer.sh ${{ matrix.server }}
+                    docker cp .github/workflows/configNC_${{ matrix.server }}.sh server:/tmp/
+                    docker exec server chmod +x /tmp/configNC_${{ matrix.server }}.sh
+                    docker exec --user www-data server /tmp/configNC_${{ matrix.server }}.sh
+                    docker exec server /usr/local/bin/run.sh
+
+            -   name: Enable KVM group perms
+                run: |
+                    echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
+                    sudo udevadm control --reload-rules
+                    sudo udevadm trigger --name-match=kvm
+
+            -   uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
+                with:
+                    distribution: "temurin"
+                    java-version: 17
+
+            -   name: create AVD and generate snapshot for caching
+                uses: reactivecircus/android-emulator-runner@6b0df4b0efb23bb0ec63d881db79aefbc976e4b2 # v2.30.1
+                with:
+                    api-level: ${{ matrix.api-level }}
+                    force-avd-creation: false
+                    arch: x86
+                    sdcard-path-or-size: 100M
+                    target: google_apis
+                    emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -skin 500x833
+                    script: echo "Generated AVD snapshot for caching."
+
+            -   name: Configure gradle daemon
+                run: |
+                    mkdir -p $HOME/.gradle
+                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > $HOME/.gradle/gradle.properties
+                    echo "org.gradle.caching=true" >> $HOME/.gradle/gradle.properties
+
+            -   name: Build gplay # TODO build only once!
                 run: |
                     sed -i s#https://server#http://10.0.2.2# gradle.properties
                     sed -i s"#1#5#" ./library/src/androidTest/java/com/owncloud/android/RetryTestRule.kt
